#+OPTIONS: ':nil *:t -:t ::t <:t H:4 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Blue Mountain Springs API
#+DATE: <2016-12-07 Wed>
#+AUTHOR: Clifford Wulfman
#+EMAIL: cwulfman@princeton.edu
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 8.3.2)


* Model of Resources

#+begin_src plantuml :file model.png
  Class Magazine {
	bmtnid : string
	uri : anyURI
	primaryTitle : string
	primaryLanguage : string
	startDate : w3cdtf
	endDate : w3cdtf
  }

  Class Issue {
	bmtnid : string
	uri : anyURI
	title  : string
	volume : string
	number : string
	pubDate : w3cdtf
	pubPlace : string
  }

  Class Constituent {
	bmtnid : string
	uri : anyURI
	title : string
	language : string
	contributor : 
	content : text
  }

  Class Contributor {
	id : string
	byline : string
  }

  BlueMountain o-- Magazine
  Magazine o-- Issue
  Issue o-- Constituent
  Constituent <|-- Contribution
  Contribution *- Contributor : < contributes
#+end_src

#+results:


* Summary of RESTful URIs (Routes)
  Each of the objects in the abstract data model maps to one or more
  RESTful URIs (routes). These are summarized below; each is described
  in greater detail in the following sections.

  - Magazine ::
    - springs/magazines
    - springs/magazines/{magazineID}

  - Issue ::
    - springs/issues/{magazineID}
    - springs/issues/{issueID}

  - Constituent ::
    - springs/constituents/{magazineID}
    - springs/constituents/{issueID}
    - springs/constituent/{issueID}/{constituentID}
    

  - Contributor ::
    - springs/contributors/{magazineID}
    - springs/contributors/{issueID}

  - Contribution :: 
    - springs/contributions?byline={string}

* Springs APIs, by Resource
** Magazines
   The /magazines/ API delivers a representation of the magazines in Blue
   Mountain.

*** springs/magazines
    When no Blue Mountain Identifier is given, the service returns a
    representation of all the magazines in Blue Mountain.

    Available Content Types:
     - text/csv
     - application/json
**** text/csv     
     A CSV stream representing the magazines in Blue Mountain. The CSV
     fields are the following:

     | Field           | Type                                           |
     |-----------------+------------------------------------------------|
     | bmtnid          | string                                         |
     | primaryTitle    | string                                         |
     | primaryLanguage | a delimited string of ISO 632-2 language codes |
     | startDate       | w3cdtf-formatted string                        |
     | endDate         | w3cdtf-formatted string                        |
     | URI             | URI to magazine /bmtnid/                       |

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept: text/csv' http://bluemountain.princeton.edu/exist/restxq/springs/magazines
     #+END_SRC

     
**** application/json
     A list of JSON objects representing the list of magazines in Blue
     Mountain. Each object has the following properties:
     | Property        | Type                                           |
     |-----------------+------------------------------------------------|
     | bmtnid          | string                                         |
     | primaryTitle    | string                                         |
     | primaryLanguage | a delimited string of ISO 632-2 language codes |
     | startDate       | w3cdtf-formatted string                        |
     | endDate         | w3cdtf-formatted string                        |
     | URI             | URI to magazine /bmtnid/                       |

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept: application/json' http://bluemountain.princeton.edu/exist/restxq/springs/magazines
     #+END_SRC


*** springs/magazines/{bmtnid}
    If a Blue Mountain magazine identifier is given, the service
   returns a representation of the corresponding magazine. The
   representation includes a set of objects representing each of the issues and,
   for each issue, a list of links to each constituent it contains.

**** application/json
     A JSON object representing the magazine.
     | Property        | Type                 |
     |-----------------+----------------------|
     | bmtnid          | string               |
     | primaryTitle    | string               |
     | primaryLanguage | { "ident" : /lang/}* |
     | startDate       | w3cdtf               |
     | endDate         | w3cdtf               |
     | url             | URI                  |
     | issue           | issue*               |
     
     Example:
     #+BEGIN_SRC sh
     curl -H'Accept: application/json' http://bluemountain.princeton.edu/exist/restxq/springs/magazines/bmtnaap
     #+END_SRC
     
** Issues
   Returns representations of magazine issues. The service behaves
   differently depending on the kind of resource that is requested.

*** springs/issues/{issueid}
   If the resource is an issue, the service returns a representation
   of the issue.

**** application/json
     Returns a JSON object with the following properties:
     | Property      | Type                                                                                                  |
     |---------------+-------------------------------------------------------------------------------------------------------|
     | bmtnid        | xs:string                                                                                             |
     | title         | xs:string                                                                                             |
     | volume        | xs:string                                                                                             |
     | number        | xs:string                                                                                             |
     | pubDate       | w3cdtf                                                                                                |
     | pubPlace      | xs:string                                                                                             |
     | editors       | list of editor objects                                                                                |
     | contributors  | list of contributor objects                                                                           |
     | contributions | lists of Illustration, TextContent, SponsoredAdvertisement, and MusicalScore objects where applicable |

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:application/json' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap_1921-11_01
     #+END_SRC

**** application/tei+xml
     An XML document conforming with the TEI schema.

     For large issues and large magazine runs, this service will
     return very large data sets in Blue Mountain 1.0. A future
     version will use status 413 to indicate an excessively large
     response and compress the response before transmission or
     implement status 207 to coordinate partial file tranfers.

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:application/tei+xml' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap_1921-11_01
     #+END_SRC

**** text/plain
     A bag of words comprising all the words in the issue.

     For large issues and large magazine runs, this service will
     return very large data sets in Blue Mountain 1.0. A future
     version will use status 413 to indicate an excessively large
     response and compress the response before transmission or
     implement status 207 to coordinate partial file tranfers.

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:text/plain' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap_1921-11_01
     #+END_SRC

**** application/rdf+xml
     In Blue Mountain version 1.0, this service is aimed primarily at
     the MODNETS aggregator, and it provides an RDF representation
     that complies with its requirements: COLLEX-flavored RDF.

     This format only supports issues; not magazines.

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:application/rdf+xml' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap_1921-11_01
     #+END_SRC

*** springs/issues/{magazineid}
    If the requested resource is a magazine, the service returns
     representations of all the issues of that magazine.

**** application/json
     A JSON object with the following properties:
     - bmtnid          :: xs:string
     - primaryTitle    :: xs:string
     - primaryLanguage :: xs:string
     - startDate       :: w3cdtf
     - endDate         :: w3cdtf
     - URI             :: xs:anyURI
     - issues          :: a list of issue objects:
       - id   :: xs:string
       - date :: w3cdtf
       - URI  :: xs:anyURI

    Example:
    #+BEGIN_SRC sh
    curl -H'Accept:application/json' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap
    #+END_SRC

**** application/tei+xml
     A teiCorpus document representing the full run of the magazine. This can be very large.

    Example:
    #+BEGIN_SRC sh
    curl -H'Accept:application/tei+xml' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap
    #+END_SRC

**** text/plain
     A bag of words containing all words in the magazine run.

    Example:
    #+BEGIN_SRC sh
    curl -H'Accept:text/plain' http://bluemountain.princeton.edu/exist/restxq/springs/issues/bmtnaap
    #+END_SRC

** Constituents
   The addressable portions of the magazine issues -- articles,
   illustrations, advertisements -- are the issue's constituents. They
   are represented in two ways:
   1) descriptive metadata about the constituent is encoded in the
      teiHeader as a relatedItem with an xml id attribute;

   2) the full text of the constituent (if it is a textual
      constituent) is encoded in a div element linked to the metadata
      element with a corresp attribute.

   The constituents service returns representations of the metadata or
   the full text, depending on the content type requested.

   The only available response type for the /constituents/ service is JSON.

*** springs/constituents/{issueid}
    A JSON object representing the id, date, and URI of the issue,
    plus a list of JSON objects representing the constituents of the
    issue. 

     - bmtnid       :: xs:string
     - date         :: w3cdtf
     - URI          :: xs:anyURI
     - constituent+ ::
       - issueid       :: xs:string
       - constituentid :: xs:string
	 - URI         :: xs:anyURI
	 - title       :: xs:string
	 - contrbutor* :: 
	   - byline        :: xs:string
	   - contributorid :: xs:string

   Example:
   #+BEGIN_SRC sh
   curl -H'Accept:application/json' http://bluemountain.princeton.edu/exist/restxq/springs/constituents/bmtnaap_1921-11_01
   #+END_SRC

*** springs/constituents/{magid}
    A JSON object with the following properties:

    - bmtnid       :: xs:string
    - date         :: w3cdtf
    - URI          :: xs:anyURI
    - constituent+ :: 
	 - URI     :: xs:anyURI

   Example:
   #+BEGIN_SRC sh
   curl -H'Accept:application/json' http://bluemountain.princeton.edu/exist/restxq/springs/constituents/bmtnaap
   #+END_SRC

** Constituent
   The /Constituent/ service delivers a representaton of an individual
   constituent in a Blue Mountain magazine issue. In Blue Mountain
   Springs 1.0, this is a representation of the constituent's
   /contents/. 

   In future versions of Blue Mountain Springs, a JSON
   request will return metadata about the constituent; for now, to get
   the metadata for a constituent, extract the JSON object from the
   representation of the issue.

*** springs/constituent/{issueid}/{constid}
    - text/plain           :: a plain-text blob.
	 #+BEGIN_SRC sh
	 curl -H'Accept:text/plain' http://bluemountain.princeton.edu/exist/restxq/springs/constituent/bmtnaap_1921-11_01/c003
	 #+END_SRC
    - application/tei+xml  :: a TEI-encoded fragment.
	 #+BEGIN_SRC sh
	 curl -H'Accept:application/tei+xml' http://bluemountain.princeton.edu/exist/restxq/springs/constituent/bmtnaap_1921-11_01/c003
	 #+END_SRC

** Contributors
   The /contributors/ service returns representations of the
   contributors to a magazine or an issue in Blue Mountain.

*** springs/contributors/{bmtnid}
    If /bmtnid/ is that of an issue, returns a representation of all the
    contributors to that issue.  If /bmtnid/ is that of a magazine,
    returns a representation of all contributors to the magazine in
    all issues.

**** text/csv
     - bmtnid        :: xs:string
     - label         :: xs:string
     - contributorid :: xs:string
     - byline        :: xs:string
     - constituentid :: xs:string
     - title         :: xs:string

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:text/csv' http://bluemountain.princeton.edu/exist/restxq/springs/contributors/bmtnaap_1921-11_01
     #+END_SRC

**** application/json
     - bmtnid        :: xs:string
     - label         :: xs:string
     - contributorid :: xs:string
     - byline        :: xs:string
     - constituentid :: xs:string
     - title         :: xs:string

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:application/json' http://bluemountain.princeton.edu/exist/restxq/springs/contributors/bmtnaap_1921-11_01
     #+END_SRC

** Contributions
   Get representation of contributions to a magazine having a
   particular byline. If the request is for JSON, returns a
   representation of the metadata for all the contributions; if the
   request is for TEI, returns a TEI Corpus containing the full text
   of all the contributions.

*** springs/contributions?byline={byline}

**** application/json
     If the request is for JSON, returns a representation of the
     metadata for all the contributions.

     - title        :: xs:string
     - byline       :: xs:string
     - language+    :: xs:string
     - issue        :: xs:anyURI
     - consttuentid :: xs:string
     - URI          :: xs:anyURI

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:application/json' http://bluemountain.princeton.edu/exist/restxq/springs/contributions?byline=Tzara
     #+END_SRC

**** application/tei+xml
     A teiCorpus document containing a set of tei:TEI elements
     representing each contribution.

     Example:
     #+BEGIN_SRC sh
     curl -H'Accept:application/tei+xml' http://bluemountain.princeton.edu/exist/restxq/springs/contributions?byline=Tzara     
     #+END_SRC
* IIIF API
  The Blue Mountain Springs service delivers text and metadata
  representations of objects in Blue Mountain. The IIIF service
  complements the Springs service; it delivers visual representations
  of Blue Mountain's resources by implementing the IIIF Presentation
  API.

  In Blue Mountain Springs 1.0, the IIIF implementation supports the
  two major IIIF resources, Collections and Manifests. These two
  resources are sufficient to enable the display of Blue Mountain's
  magazines in IIIF-compliant viewing software. It has been tested
  with Mirador and the UniversalViewer.

  IIIF collections and manifests are represented as JSON objects.

** iiif/collection/top
   A IIIF collection object representing all the resources in Blue
   Mountain.

   Example:
   #+BEGIN_SRC sh
   curl http://bluemountain.princeton.edu/exist/restxq/iiif/collection/top
   #+END_SRC

** iiif/collection/{magid}
   A IIIF collection object representing a magazine in Blue Mountain.

   Example:
   #+BEGIN_SRC sh
   curl http://bluemountain.princeton.edu/exist/restxq/iiif/collection/bmtnaap
   #+END_SRC

** iiif/manifest/{issueid}
   A IIIF manifest object representing a particular issue.

   Example:
   #+BEGIN_SRC sh
   curl http://bluemountain.princeton.edu/exist/restxq/iiif/manifest/bmtnaap_1921-11_01
   #+END_SRC
